<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Starter Home',
                'slug' => 'starter-home',
                'type' => 'residential',
                'download_mbps' => 30,
                'upload_mbps' => 30,
                'price_monthly' => 1000,
                'installation_fee' => 500,
                'billing_label' => 'per month',
                'description' => 'Everyday browsing, social media and video calls for the whole family.',
                'features' => [
                    '30 Mbps symmetric fiber',
                    'Unlimited data',
                    'Dual-band WiFi router included',
                    'Free professional installation',
                ],
                'attributes' => [
                    'connection' => 'Fiber to the home',
                    'support' => '24/7 local support',
                    'router' => 'Dual-band WiFi router',
                    'static_ip' => false,
                    'sla' => 'Best effort',
                ],
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 1,
            ],
            [
                'name' => 'Plus Home',
                'slug' => 'plus-home',
                'type' => 'residential',
                'download_mbps' => 50,
                'upload_mbps' => 50,
                'price_monthly' => 1400,
                'installation_fee' => 500,
                'billing_label' => 'per month',
                'description' => 'Effortless HD streaming, online classes and smooth video meetings.',
                'features' => [
                    '50 Mbps symmetric fiber',
                    'Unlimited data',
                    'Dual-band WiFi router included',
                    'Free professional installation',
                    'Priority support',
                ],
                'attributes' => [
                    'connection' => 'Fiber to the home',
                    'support' => 'Priority 24/7 support',
                    'router' => 'Dual-band WiFi router',
                    'static_ip' => false,
                    'sla' => 'Best effort',
                ],
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 2,
            ],
            [
                'name' => 'Pro Home',
                'slug' => 'pro-home',
                'type' => 'residential',
                'download_mbps' => 100,
                'upload_mbps' => 100,
                'price_monthly' => 1900,
                'original_price' => 2200,
                'promo_price' => 1900,
                'promo_label' => 'This month only',
                'promo_description' => 'Lock in ৳1,900 for the first six months, then ৳2,200/month.',
                'promo_ends_at' => now()->addMonths(1)->toDateString(),
                'installation_fee' => 0,
                'billing_label' => 'per month',
                'description' => 'Ultra-fast fiber built for 4K streaming, gaming and remote work.',
                'features' => [
                    '100 Mbps symmetric fiber',
                    'Unlimited data',
                    'WiFi 6 router included',
                    'Free professional installation',
                    'Priority support',
                    'Static IP on request',
                ],
                'attributes' => [
                    'connection' => 'Fiber to the home',
                    'support' => 'Priority 24/7 support',
                    'router' => 'WiFi 6 router',
                    'static_ip' => true,
                    'sla' => 'Best effort',
                ],
                'badge' => 'Most Popular',
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Ultra Home',
                'slug' => 'ultra-home',
                'type' => 'residential',
                'download_mbps' => 200,
                'upload_mbps' => 200,
                'price_monthly' => 2900,
                'installation_fee' => 0,
                'billing_label' => 'per month',
                'description' => 'The fastest home tier — for creators, power users and large households.',
                'features' => [
                    '200 Mbps symmetric fiber',
                    'Unlimited data',
                    'WiFi 6 router included',
                    'Free professional installation',
                    'Priority support',
                    'Static IP on request',
                ],
                'attributes' => [
                    'connection' => 'Fiber to the home',
                    'support' => 'Priority 24/7 support',
                    'router' => 'WiFi 6 router',
                    'static_ip' => true,
                    'sla' => 'Best effort',
                ],
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'name' => 'Business Pro',
                'slug' => 'business-pro',
                'type' => 'business',
                'download_mbps' => 100,
                'upload_mbps' => 100,
                'price_monthly' => 3500,
                'installation_fee' => 0,
                'billing_label' => 'per month',
                'description' => 'Dependable business connectivity with a service-level agreement.',
                'features' => [
                    '100 Mbps symmetric fiber',
                    'Unlimited data',
                    'Static IP included',
                    '99.9% uptime SLA',
                    'Dedicated account manager',
                ],
                'attributes' => [
                    'connection' => 'Dedicated fiber',
                    'support' => 'Dedicated account manager',
                    'router' => 'Business router',
                    'static_ip' => true,
                    'sla' => '99.9% SLA',
                ],
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Business Enterprise',
                'slug' => 'business-enterprise',
                'type' => 'business',
                'download_mbps' => 500,
                'upload_mbps' => 500,
                'price_monthly' => 7500,
                'installation_fee' => 0,
                'billing_label' => 'per month',
                'description' => 'High-capacity connectivity for offices, studios and growing companies.',
                'features' => [
                    '500 Mbps symmetric fiber',
                    'Unlimited data',
                    'Static IP included',
                    '99.9% uptime SLA',
                    'Dedicated account manager',
                    'Redundant routing',
                ],
                'attributes' => [
                    'connection' => 'Dedicated fiber',
                    'support' => 'Dedicated account manager',
                    'router' => 'Business router',
                    'static_ip' => true,
                    'sla' => '99.9% SLA',
                ],
                'badge' => null,
                'is_featured' => false,
                'sort_order' => 6,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::query()->updateOrCreate(['slug' => $plan['slug']], $plan);
        }
    }
}
